export { default as logo } from '../assets/images/logo.webp';
export { default as classesandevents } from '../assets/images/classes-and-events.webp';
export { default as merch } from '../assets/images/merchs.webp';
export { default as bg } from '../assets/images/bg.webp';
export { default as productions } from '../assets/images/productions.webp';
export { default as headlogo } from '../assets/images/headlogo.webp';
export { default as lession } from '../assets/images/lessons.webp';
export { default as servicesCover } from '../assets/images/services_cover.webp';
export { default as loginbg } from '../assets/images/sign-in-bg.webp';
export { default as moto } from '../assets/videos/moto.mp4';
export { default as bggradiant} from '../assets/images/bg-gradiant.webp';
export { default as augustIntake } from '../assets/images/events/audust-new-intake.webp';
export { default as wannam} from '../assets/images/events/thumb-nail.webp';
export { default as TheDancerEYNK} from '../assets/images/TheDancer EYNK.webp';